// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: control.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HelloRequest carries the client's compiled-in version. The handshake is the
// AUTHORITATIVE version check.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

// HelloReply carries the server's authoritative version plus liveness hints.
//
// VERSION POLICY: only a client STRICTLY NEWER than the running server relaunches
// it (drain + relaunch under the single-winner lock); an OLDER client degrades to
// a clear "server is newer, upgrade your client" error (it cannot produce a newer
// server). A dev build (empty version) is treated as always-compatible.
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	// pid is a HOST-LOCAL hint, usable only by a LOCAL client for restart
	// confirmation. A REMOTE client gets a meaningless pid and MUST rely on
	// server_version + started_at to detect a restart — keeping the contract free
	// of localhost assumptions.
	Pid           int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HelloReply) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *HelloReply) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// ShutdownRequest asks the server to drain in-flight jobs and exit. drain=true
// (the version-upgrade path) waits for running jobs to finish before exiting;
// drain=false is reserved (force-exit). reason is free-form for the event log.
type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drain         bool                   `protobuf:"varint,1,opt,name=drain,proto3" json:"drain,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *ShutdownRequest) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

func (x *ShutdownRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// ShutdownReply confirms acceptance and reports how many jobs will be drained
// (snapshotted in the same model-loop turn that flips to draining), so the
// caller can show progress.
type ShutdownReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	DrainingJobs  int32                  `protobuf:"varint,2,opt,name=draining_jobs,json=drainingJobs,proto3" json:"draining_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownReply) Reset() {
	*x = ShutdownReply{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownReply) ProtoMessage() {}

func (x *ShutdownReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownReply.ProtoReflect.Descriptor instead.
func (*ShutdownReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *ShutdownReply) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ShutdownReply) GetDrainingJobs() int32 {
	if x != nil {
		return x.DrainingJobs
	}
	return 0
}

// FleetTUIConnectedRequest signals that a TUI client has just opened (sent once
// per TUI launch, NOT per CLI command — CLI invocations only Hello). The server
// uses it as a hook for once-per-open, fire-and-forget state reconciliation —
// today: re-ensuring any configured shared buildkit servers that were killed
// externally / lost to a host reboot while no instance lifecycle action would
// have revived them. Empty by design; it is a pure nudge. Multiple TUIs may
// send it concurrently, so the server coalesces the work.
type FleetTUIConnectedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetTUIConnectedRequest) Reset() {
	*x = FleetTUIConnectedRequest{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetTUIConnectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetTUIConnectedRequest) ProtoMessage() {}

func (x *FleetTUIConnectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetTUIConnectedRequest.ProtoReflect.Descriptor instead.
func (*FleetTUIConnectedRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

// FleetTUIConnectedReply is intentionally empty: the reconciliation is
// fire-and-forget on the server, so the client does not wait on its outcome.
type FleetTUIConnectedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetTUIConnectedReply) Reset() {
	*x = FleetTUIConnectedReply{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetTUIConnectedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetTUIConnectedReply) ProtoMessage() {}

func (x *FleetTUIConnectedReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetTUIConnectedReply.ProtoReflect.Descriptor instead.
func (*FleetTUIConnectedReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

// DeleteBuildkitCacheRequest asks the server to wipe a fleet's shared build
// cache: stop the buildkit container, clear the CONTENTS of
// ~/.fleet/workspaces/<fleet>/.buildkit (incl. the root-owned cache) while
// KEEPING the directory itself so running instances' bind mounts stay valid,
// then restart the server empty. It is a synchronous action (takes a few
// seconds), so the client shows progress and uses a longer deadline than
// ordinary mutations.
type DeleteBuildkitCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuildkitCacheRequest) Reset() {
	*x = DeleteBuildkitCacheRequest{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildkitCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildkitCacheRequest) ProtoMessage() {}

func (x *DeleteBuildkitCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildkitCacheRequest.ProtoReflect.Descriptor instead.
func (*DeleteBuildkitCacheRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBuildkitCacheRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

// DeleteBuildkitCacheReply is empty: success is signalled by a nil error.
type DeleteBuildkitCacheReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuildkitCacheReply) Reset() {
	*x = DeleteBuildkitCacheReply{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildkitCacheReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildkitCacheReply) ProtoMessage() {}

func (x *DeleteBuildkitCacheReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildkitCacheReply.ProtoReflect.Descriptor instead.
func (*DeleteBuildkitCacheReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

// DeleteDebCacheRequest asks the server to wipe a fleet's shared deb (apt)
// cache: remove the apt-cacher-ng container, clear the CONTENTS of
// ~/.fleet/workspaces/<fleet>/.aptcache while keeping the directory, then
// restart the server empty. Synchronous (a few seconds), like DeleteBuildkitCache.
type DeleteDebCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDebCacheRequest) Reset() {
	*x = DeleteDebCacheRequest{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDebCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDebCacheRequest) ProtoMessage() {}

func (x *DeleteDebCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDebCacheRequest.ProtoReflect.Descriptor instead.
func (*DeleteDebCacheRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDebCacheRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

// DeleteDebCacheReply is empty: success is signalled by a nil error.
type DeleteDebCacheReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDebCacheReply) Reset() {
	*x = DeleteDebCacheReply{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDebCacheReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDebCacheReply) ProtoMessage() {}

func (x *DeleteDebCacheReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDebCacheReply.ProtoReflect.Descriptor instead.
func (*DeleteDebCacheReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

// DeleteImageCacheRequest asks the server to wipe a fleet's shared docker image
// (registry pull-through) cache: remove the registry container, clear the
// CONTENTS of ~/.fleet/workspaces/<fleet>/.imgcache while keeping the directory,
// then restart the server empty. Synchronous, like DeleteBuildkitCache.
type DeleteImageCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageCacheRequest) Reset() {
	*x = DeleteImageCacheRequest{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageCacheRequest) ProtoMessage() {}

func (x *DeleteImageCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageCacheRequest.ProtoReflect.Descriptor instead.
func (*DeleteImageCacheRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteImageCacheRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

// DeleteImageCacheReply is empty: success is signalled by a nil error.
type DeleteImageCacheReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageCacheReply) Reset() {
	*x = DeleteImageCacheReply{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageCacheReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageCacheReply) ProtoMessage() {}

func (x *DeleteImageCacheReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageCacheReply.ProtoReflect.Descriptor instead.
func (*DeleteImageCacheReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

// GetStateReply is the one-stop snapshot of EVERYTHING the TUI renders:
//
//	state   — persisted: what fleets/instances exist + their recorded status
//	runtime — live: agent running?/stats/sessions/ports/live container status
//	active_jobs — in-flight jobs (for progress + re-attach)
type GetStateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Runtime       []*InstanceRuntime     `protobuf:"bytes,2,rep,name=runtime,proto3" json:"runtime,omitempty"`
	ActiveJobs    []*JobSummary          `protobuf:"bytes,3,rep,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateReply) Reset() {
	*x = GetStateReply{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateReply) ProtoMessage() {}

func (x *GetStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateReply.ProtoReflect.Descriptor instead.
func (*GetStateReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *GetStateReply) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GetStateReply) GetRuntime() []*InstanceRuntime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *GetStateReply) GetActiveJobs() []*JobSummary {
	if x != nil {
		return x.ActiveJobs
	}
	return nil
}

// CreateFleet adds a fleet (GetOrCreateFleet). Idempotent: returns the existing
// fleet if present.
type CreateFleetRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remote string                 `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`
	// Absolute path (on the DAEMON host) of an existing folder. When set, this is
	// a "local folder" fleet: remote is empty and its single instance bind-mounts
	// the folder in place. See CreateInstanceRequest.source_path.
	SourcePath    *string `protobuf:"bytes,3,opt,name=source_path,json=sourcePath,proto3,oneof" json:"source_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFleetRequest) Reset() {
	*x = CreateFleetRequest{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFleetRequest) ProtoMessage() {}

func (x *CreateFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFleetRequest.ProtoReflect.Descriptor instead.
func (*CreateFleetRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *CreateFleetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFleetRequest) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *CreateFleetRequest) GetSourcePath() string {
	if x != nil && x.SourcePath != nil {
		return *x.SourcePath
	}
	return ""
}

// DestroyFleet removes the fleet RECORD only (no container teardown — that is
// DestroyInstance with destroy_fleet). The server REJECTS this when live
// instances remain, to prevent orphaned containers.
type DestroyFleetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyFleetRequest) Reset() {
	*x = DestroyFleetRequest{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyFleetRequest) ProtoMessage() {}

func (x *DestroyFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyFleetRequest.ProtoReflect.Descriptor instead.
func (*DestroyFleetRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *DestroyFleetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// SetFleetSettings replaces a fleet's mount/home/launch settings. Sending the
// full FleetSettings keeps presence semantics (e.g. prefer_fleet_launch
// tri-state) intact.
type SetFleetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Settings      *FleetSettings         `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFleetSettingsRequest) Reset() {
	*x = SetFleetSettingsRequest{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFleetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFleetSettingsRequest) ProtoMessage() {}

func (x *SetFleetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFleetSettingsRequest.ProtoReflect.Descriptor instead.
func (*SetFleetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *SetFleetSettingsRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *SetFleetSettingsRequest) GetSettings() *FleetSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// SetInstanceMetadata updates user-facing labels without touching resources
// (RENAME display_name+color, TAG tag). Fields are optional so a caller updates
// one without clobbering the others; an explicit empty string (clear tag) is
// sent via the presence bit.
type SetInstanceMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	DisplayName   *string                `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Color         *string                `protobuf:"bytes,4,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Tag           *string                `protobuf:"bytes,5,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInstanceMetadataRequest) Reset() {
	*x = SetInstanceMetadataRequest{}
	mi := &file_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInstanceMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInstanceMetadataRequest) ProtoMessage() {}

func (x *SetInstanceMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInstanceMetadataRequest.ProtoReflect.Descriptor instead.
func (*SetInstanceMetadataRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{17}
}

func (x *SetInstanceMetadataRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *SetInstanceMetadataRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *SetInstanceMetadataRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *SetInstanceMetadataRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *SetInstanceMetadataRequest) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

// SetGroupLayout persists a tmux pane layout (SAVE_GROUP_LAYOUT). The state map
// is keyed by computeGroupKey(instance_name, group_id); the server derives that
// composite key from the GroupLayout's own fields.
type SetGroupLayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layout        *GroupLayout           `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupLayoutRequest) Reset() {
	*x = SetGroupLayoutRequest{}
	mi := &file_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupLayoutRequest) ProtoMessage() {}

func (x *SetGroupLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupLayoutRequest.ProtoReflect.Descriptor instead.
func (*SetGroupLayoutRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{18}
}

func (x *SetGroupLayoutRequest) GetLayout() *GroupLayout {
	if x != nil {
		return x.Layout
	}
	return nil
}

// DeleteGroupLayout removes a persisted layout (the delete(st.GroupLayouts, key)
// sites when a group/instance is gone). The server derives the same composite
// key and removes the entry — without this, deleted-pane layouts would resurrect.
type DeleteGroupLayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceName  string                 `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupLayoutRequest) Reset() {
	*x = DeleteGroupLayoutRequest{}
	mi := &file_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupLayoutRequest) ProtoMessage() {}

func (x *DeleteGroupLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupLayoutRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupLayoutRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteGroupLayoutRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *DeleteGroupLayoutRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// SetLastSeenVersion records the release-notes version the user has seen.
type SetLastSeenVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLastSeenVersionRequest) Reset() {
	*x = SetLastSeenVersionRequest{}
	mi := &file_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLastSeenVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLastSeenVersionRequest) ProtoMessage() {}

func (x *SetLastSeenVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLastSeenVersionRequest.ProtoReflect.Descriptor instead.
func (*SetLastSeenVersionRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{20}
}

func (x *SetLastSeenVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Generic reply for the synchronous mutations: the post-mutation State.
type MutationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationReply) Reset() {
	*x = MutationReply{}
	mi := &file_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationReply) ProtoMessage() {}

func (x *MutationReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationReply.ProtoReflect.Descriptor instead.
func (*MutationReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{21}
}

func (x *MutationReply) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\tfleetgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fdomain.proto\x1a\rruntime.proto\x1a\n" +
	"jobs.proto\"5\n" +
	"\fHelloRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\"\x80\x01\n" +
	"\n" +
	"HelloReply\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"O\n" +
	"\x0fShutdownRequest\x12\x14\n" +
	"\x05drain\x18\x01 \x01(\bR\x05drain\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"P\n" +
	"\rShutdownReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rdraining_jobs\x18\x02 \x01(\x05R\fdrainingJobs\"\x1a\n" +
	"\x18FleetTUIConnectedRequest\"\x18\n" +
	"\x16FleetTUIConnectedReply\"2\n" +
	"\x1aDeleteBuildkitCacheRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\"\x1a\n" +
	"\x18DeleteBuildkitCacheReply\"-\n" +
	"\x15DeleteDebCacheRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\"\x15\n" +
	"\x13DeleteDebCacheReply\"/\n" +
	"\x17DeleteImageCacheRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\"\x17\n" +
	"\x15DeleteImageCacheReply\"\x11\n" +
	"\x0fGetStateRequest\"\xa5\x01\n" +
	"\rGetStateReply\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.fleetgrpc.StateR\x05state\x124\n" +
	"\aruntime\x18\x02 \x03(\v2\x1a.fleetgrpc.InstanceRuntimeR\aruntime\x126\n" +
	"\vactive_jobs\x18\x03 \x03(\v2\x15.fleetgrpc.JobSummaryR\n" +
	"activeJobs\"v\n" +
	"\x12CreateFleetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06remote\x18\x02 \x01(\tR\x06remote\x12$\n" +
	"\vsource_path\x18\x03 \x01(\tH\x00R\n" +
	"sourcePath\x88\x01\x01B\x0e\n" +
	"\f_source_path\")\n" +
	"\x13DestroyFleetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"e\n" +
	"\x17SetFleetSettingsRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x124\n" +
	"\bsettings\x18\x02 \x01(\v2\x18.fleetgrpc.FleetSettingsR\bsettings\"\xcb\x01\n" +
	"\x1aSetInstanceMetadataRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x04 \x01(\tH\x01R\x05color\x88\x01\x01\x12\x15\n" +
	"\x03tag\x18\x05 \x01(\tH\x02R\x03tag\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\b\n" +
	"\x06_colorB\x06\n" +
	"\x04_tag\"G\n" +
	"\x15SetGroupLayoutRequest\x12.\n" +
	"\x06layout\x18\x01 \x01(\v2\x16.fleetgrpc.GroupLayoutR\x06layout\"Z\n" +
	"\x18DeleteGroupLayoutRequest\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"5\n" +
	"\x19SetLastSeenVersionRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"7\n" +
	"\rMutationReply\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.fleetgrpc.StateR\x05stateB:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_control_proto_goTypes = []any{
	(*HelloRequest)(nil),               // 0: fleetgrpc.HelloRequest
	(*HelloReply)(nil),                 // 1: fleetgrpc.HelloReply
	(*ShutdownRequest)(nil),            // 2: fleetgrpc.ShutdownRequest
	(*ShutdownReply)(nil),              // 3: fleetgrpc.ShutdownReply
	(*FleetTUIConnectedRequest)(nil),   // 4: fleetgrpc.FleetTUIConnectedRequest
	(*FleetTUIConnectedReply)(nil),     // 5: fleetgrpc.FleetTUIConnectedReply
	(*DeleteBuildkitCacheRequest)(nil), // 6: fleetgrpc.DeleteBuildkitCacheRequest
	(*DeleteBuildkitCacheReply)(nil),   // 7: fleetgrpc.DeleteBuildkitCacheReply
	(*DeleteDebCacheRequest)(nil),      // 8: fleetgrpc.DeleteDebCacheRequest
	(*DeleteDebCacheReply)(nil),        // 9: fleetgrpc.DeleteDebCacheReply
	(*DeleteImageCacheRequest)(nil),    // 10: fleetgrpc.DeleteImageCacheRequest
	(*DeleteImageCacheReply)(nil),      // 11: fleetgrpc.DeleteImageCacheReply
	(*GetStateRequest)(nil),            // 12: fleetgrpc.GetStateRequest
	(*GetStateReply)(nil),              // 13: fleetgrpc.GetStateReply
	(*CreateFleetRequest)(nil),         // 14: fleetgrpc.CreateFleetRequest
	(*DestroyFleetRequest)(nil),        // 15: fleetgrpc.DestroyFleetRequest
	(*SetFleetSettingsRequest)(nil),    // 16: fleetgrpc.SetFleetSettingsRequest
	(*SetInstanceMetadataRequest)(nil), // 17: fleetgrpc.SetInstanceMetadataRequest
	(*SetGroupLayoutRequest)(nil),      // 18: fleetgrpc.SetGroupLayoutRequest
	(*DeleteGroupLayoutRequest)(nil),   // 19: fleetgrpc.DeleteGroupLayoutRequest
	(*SetLastSeenVersionRequest)(nil),  // 20: fleetgrpc.SetLastSeenVersionRequest
	(*MutationReply)(nil),              // 21: fleetgrpc.MutationReply
	(*timestamppb.Timestamp)(nil),      // 22: google.protobuf.Timestamp
	(*State)(nil),                      // 23: fleetgrpc.State
	(*InstanceRuntime)(nil),            // 24: fleetgrpc.InstanceRuntime
	(*JobSummary)(nil),                 // 25: fleetgrpc.JobSummary
	(*FleetSettings)(nil),              // 26: fleetgrpc.FleetSettings
	(*GroupLayout)(nil),                // 27: fleetgrpc.GroupLayout
}
var file_control_proto_depIdxs = []int32{
	22, // 0: fleetgrpc.HelloReply.started_at:type_name -> google.protobuf.Timestamp
	23, // 1: fleetgrpc.GetStateReply.state:type_name -> fleetgrpc.State
	24, // 2: fleetgrpc.GetStateReply.runtime:type_name -> fleetgrpc.InstanceRuntime
	25, // 3: fleetgrpc.GetStateReply.active_jobs:type_name -> fleetgrpc.JobSummary
	26, // 4: fleetgrpc.SetFleetSettingsRequest.settings:type_name -> fleetgrpc.FleetSettings
	27, // 5: fleetgrpc.SetGroupLayoutRequest.layout:type_name -> fleetgrpc.GroupLayout
	23, // 6: fleetgrpc.MutationReply.state:type_name -> fleetgrpc.State
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_domain_proto_init()
	file_runtime_proto_init()
	file_jobs_proto_init()
	file_control_proto_msgTypes[2].OneofWrappers = []any{}
	file_control_proto_msgTypes[14].OneofWrappers = []any{}
	file_control_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
