// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jobs.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobKind tags what a job is doing so a re-attaching watcher knows the shape of
// progress to expect.
type JobKind int32

const (
	JobKind_JOB_KIND_UNSPECIFIED      JobKind = 0
	JobKind_JOB_KIND_CREATE_INSTANCE  JobKind = 1
	JobKind_JOB_KIND_DESTROY_INSTANCE JobKind = 2
	JobKind_JOB_KIND_START_INSTANCE   JobKind = 3
	JobKind_JOB_KIND_STOP_INSTANCE    JobKind = 4
	JobKind_JOB_KIND_CLONE_INSTANCE   JobKind = 5
	JobKind_JOB_KIND_REBUILD_INSTANCE JobKind = 6
)

// Enum value maps for JobKind.
var (
	JobKind_name = map[int32]string{
		0: "JOB_KIND_UNSPECIFIED",
		1: "JOB_KIND_CREATE_INSTANCE",
		2: "JOB_KIND_DESTROY_INSTANCE",
		3: "JOB_KIND_START_INSTANCE",
		4: "JOB_KIND_STOP_INSTANCE",
		5: "JOB_KIND_CLONE_INSTANCE",
		6: "JOB_KIND_REBUILD_INSTANCE",
	}
	JobKind_value = map[string]int32{
		"JOB_KIND_UNSPECIFIED":      0,
		"JOB_KIND_CREATE_INSTANCE":  1,
		"JOB_KIND_DESTROY_INSTANCE": 2,
		"JOB_KIND_START_INSTANCE":   3,
		"JOB_KIND_STOP_INSTANCE":    4,
		"JOB_KIND_CLONE_INSTANCE":   5,
		"JOB_KIND_REBUILD_INSTANCE": 6,
	}
)

func (x JobKind) Enum() *JobKind {
	p := new(JobKind)
	*p = x
	return p
}

func (x JobKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobKind) Descriptor() protoreflect.EnumDescriptor {
	return file_jobs_proto_enumTypes[0].Descriptor()
}

func (JobKind) Type() protoreflect.EnumType {
	return &file_jobs_proto_enumTypes[0]
}

func (x JobKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobKind.Descriptor instead.
func (JobKind) EnumDescriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{0}
}

// JobStep enumerates the discrete provisioning/lifecycle steps (create.Run /
// instanceops / destroy). A typed enum lets the TUI render a stable progress
// checklist; DONE marks terminal success.
type JobStep int32

const (
	JobStep_JOB_STEP_UNSPECIFIED          JobStep = 0
	JobStep_JOB_STEP_VALIDATE_BACKEND     JobStep = 1
	JobStep_JOB_STEP_BUILD_BACKEND        JobStep = 2
	JobStep_JOB_STEP_GIT_CLONE            JobStep = 3
	JobStep_JOB_STEP_RESOLVE_MOUNTS       JobStep = 4
	JobStep_JOB_STEP_CONTROL_MOUNT        JobStep = 5
	JobStep_JOB_STEP_BACKEND_UP           JobStep = 6
	JobStep_JOB_STEP_STAGE_FLEET_LAUNCH   JobStep = 7
	JobStep_JOB_STEP_STAGE_FLEET_RC       JobStep = 8
	JobStep_JOB_STEP_APPLY_MOUNT_SYMLINKS JobStep = 9
	JobStep_JOB_STEP_INSTALL_DOTFILES     JobStep = 10
	JobStep_JOB_STEP_RUN_STARTUP_SCRIPTS  JobStep = 11
	JobStep_JOB_STEP_INSTALL_CLAUDE_HOOKS JobStep = 12
	JobStep_JOB_STEP_COPY_WORKSPACE       JobStep = 13 // clone-only
	JobStep_JOB_STEP_BACKEND_CLONE        JobStep = 14 // clone-only
	JobStep_JOB_STEP_BACKEND_DOWN         JobStep = 15 // destroy / stop
	JobStep_JOB_STEP_REMOVE_WORKSPACE     JobStep = 16 // destroy (os.RemoveAll workspaceDir)
	JobStep_JOB_STEP_BACKEND_START        JobStep = 17 // start
	JobStep_JOB_STEP_MARK_RUNNING         JobStep = 18
	JobStep_JOB_STEP_DONE                 JobStep = 19
)

// Enum value maps for JobStep.
var (
	JobStep_name = map[int32]string{
		0:  "JOB_STEP_UNSPECIFIED",
		1:  "JOB_STEP_VALIDATE_BACKEND",
		2:  "JOB_STEP_BUILD_BACKEND",
		3:  "JOB_STEP_GIT_CLONE",
		4:  "JOB_STEP_RESOLVE_MOUNTS",
		5:  "JOB_STEP_CONTROL_MOUNT",
		6:  "JOB_STEP_BACKEND_UP",
		7:  "JOB_STEP_STAGE_FLEET_LAUNCH",
		8:  "JOB_STEP_STAGE_FLEET_RC",
		9:  "JOB_STEP_APPLY_MOUNT_SYMLINKS",
		10: "JOB_STEP_INSTALL_DOTFILES",
		11: "JOB_STEP_RUN_STARTUP_SCRIPTS",
		12: "JOB_STEP_INSTALL_CLAUDE_HOOKS",
		13: "JOB_STEP_COPY_WORKSPACE",
		14: "JOB_STEP_BACKEND_CLONE",
		15: "JOB_STEP_BACKEND_DOWN",
		16: "JOB_STEP_REMOVE_WORKSPACE",
		17: "JOB_STEP_BACKEND_START",
		18: "JOB_STEP_MARK_RUNNING",
		19: "JOB_STEP_DONE",
	}
	JobStep_value = map[string]int32{
		"JOB_STEP_UNSPECIFIED":          0,
		"JOB_STEP_VALIDATE_BACKEND":     1,
		"JOB_STEP_BUILD_BACKEND":        2,
		"JOB_STEP_GIT_CLONE":            3,
		"JOB_STEP_RESOLVE_MOUNTS":       4,
		"JOB_STEP_CONTROL_MOUNT":        5,
		"JOB_STEP_BACKEND_UP":           6,
		"JOB_STEP_STAGE_FLEET_LAUNCH":   7,
		"JOB_STEP_STAGE_FLEET_RC":       8,
		"JOB_STEP_APPLY_MOUNT_SYMLINKS": 9,
		"JOB_STEP_INSTALL_DOTFILES":     10,
		"JOB_STEP_RUN_STARTUP_SCRIPTS":  11,
		"JOB_STEP_INSTALL_CLAUDE_HOOKS": 12,
		"JOB_STEP_COPY_WORKSPACE":       13,
		"JOB_STEP_BACKEND_CLONE":        14,
		"JOB_STEP_BACKEND_DOWN":         15,
		"JOB_STEP_REMOVE_WORKSPACE":     16,
		"JOB_STEP_BACKEND_START":        17,
		"JOB_STEP_MARK_RUNNING":         18,
		"JOB_STEP_DONE":                 19,
	}
)

func (x JobStep) Enum() *JobStep {
	p := new(JobStep)
	*p = x
	return p
}

func (x JobStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStep) Descriptor() protoreflect.EnumDescriptor {
	return file_jobs_proto_enumTypes[1].Descriptor()
}

func (JobStep) Type() protoreflect.EnumType {
	return &file_jobs_proto_enumTypes[1]
}

func (x JobStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStep.Descriptor instead.
func (JobStep) EnumDescriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{1}
}

// LogLevel classifies a JobLog line. WARN replaces the legacy non-fatal
// state.WriteWarn surface (the TUI's old .warn-file polling): warnings now flow
// inline on the job/Watch stream.
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_INFO        LogLevel = 1
	LogLevel_LOG_LEVEL_WARN        LogLevel = 2
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_INFO",
		2: "LOG_LEVEL_WARN",
		3: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_INFO":        1,
		"LOG_LEVEL_WARN":        2,
		"LOG_LEVEL_ERROR":       3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_jobs_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_jobs_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{2}
}

// JobSummary describes an in-flight (or just-completed) job so a watcher that did
// NOT launch the job can LEARN its job_id and re-attach. Carried on
// GetStateReply and the initial Watch snapshot.
type JobSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Kind          JobKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=fleetgrpc.JobKind" json:"kind,omitempty"`
	Fleet         string                 `protobuf:"bytes,3,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
	CurrentStep   JobStep                `protobuf:"varint,5,opt,name=current_step,json=currentStep,proto3,enum=fleetgrpc.JobStep" json:"current_step,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSummary) Reset() {
	*x = JobSummary{}
	mi := &file_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSummary) ProtoMessage() {}

func (x *JobSummary) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSummary.ProtoReflect.Descriptor instead.
func (*JobSummary) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *JobSummary) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSummary) GetKind() JobKind {
	if x != nil {
		return x.Kind
	}
	return JobKind_JOB_KIND_UNSPECIFIED
}

func (x *JobSummary) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *JobSummary) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *JobSummary) GetCurrentStep() JobStep {
	if x != nil {
		return x.CurrentStep
	}
	return JobStep_JOB_STEP_UNSPECIFIED
}

func (x *JobSummary) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// JobEvent is one item of a job RPC's server stream. CONTRACT: the FIRST event on
// every job stream MUST be a `started` so a client whose process dies can later
// re-attach via Watch.reattach_job_ids. The terminal event is always a `done`.
// job_id is carried ONCE here, on the envelope, and is authoritative; the inner
// payloads do NOT repeat it.
type JobEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*JobEvent_Started
	//	*JobEvent_Progress
	//	*JobEvent_Log
	//	*JobEvent_Done
	Event         isJobEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEvent) Reset() {
	*x = JobEvent{}
	mi := &file_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEvent) ProtoMessage() {}

func (x *JobEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEvent.ProtoReflect.Descriptor instead.
func (*JobEvent) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *JobEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobEvent) GetEvent() isJobEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *JobEvent) GetStarted() *JobStarted {
	if x != nil {
		if x, ok := x.Event.(*JobEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *JobEvent) GetProgress() *JobProgress {
	if x != nil {
		if x, ok := x.Event.(*JobEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *JobEvent) GetLog() *JobLog {
	if x != nil {
		if x, ok := x.Event.(*JobEvent_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *JobEvent) GetDone() *JobDone {
	if x != nil {
		if x, ok := x.Event.(*JobEvent_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isJobEvent_Event interface {
	isJobEvent_Event()
}

type JobEvent_Started struct {
	Started *JobStarted `protobuf:"bytes,2,opt,name=started,proto3,oneof"`
}

type JobEvent_Progress struct {
	Progress *JobProgress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type JobEvent_Log struct {
	Log *JobLog `protobuf:"bytes,4,opt,name=log,proto3,oneof"`
}

type JobEvent_Done struct {
	Done *JobDone `protobuf:"bytes,5,opt,name=done,proto3,oneof"`
}

func (*JobEvent_Started) isJobEvent_Event() {}

func (*JobEvent_Progress) isJobEvent_Event() {}

func (*JobEvent_Log) isJobEvent_Event() {}

func (*JobEvent_Done) isJobEvent_Event() {}

// JobStarted is the mandatory first event. It carries its own job_id so it is
// self-describing when surfaced via Event (watch.proto), whose oneof has no
// job_id envelope. Echoes kind + target + start time for labeling.
type JobStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Kind          JobKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=fleetgrpc.JobKind" json:"kind,omitempty"`
	Fleet         string                 `protobuf:"bytes,3,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStarted) Reset() {
	*x = JobStarted{}
	mi := &file_jobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStarted) ProtoMessage() {}

func (x *JobStarted) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStarted.ProtoReflect.Descriptor instead.
func (*JobStarted) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{2}
}

func (x *JobStarted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStarted) GetKind() JobKind {
	if x != nil {
		return x.Kind
	}
	return JobKind_JOB_KIND_UNSPECIFIED
}

func (x *JobStarted) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *JobStarted) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *JobStarted) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// JobProgress reports advancing through a JobStep. step_done marks the step
// complete (vs just-entered) so the TUI can tick a checklist. percent is
// optional (most steps aren't quantifiable).
type JobProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          JobStep                `protobuf:"varint,1,opt,name=step,proto3,enum=fleetgrpc.JobStep" json:"step,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StepDone      bool                   `protobuf:"varint,3,opt,name=step_done,json=stepDone,proto3" json:"step_done,omitempty"`
	Percent       *float32               `protobuf:"fixed32,4,opt,name=percent,proto3,oneof" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobProgress) Reset() {
	*x = JobProgress{}
	mi := &file_jobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgress) ProtoMessage() {}

func (x *JobProgress) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgress.ProtoReflect.Descriptor instead.
func (*JobProgress) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *JobProgress) GetStep() JobStep {
	if x != nil {
		return x.Step
	}
	return JobStep_JOB_STEP_UNSPECIFIED
}

func (x *JobProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobProgress) GetStepDone() bool {
	if x != nil {
		return x.StepDone
	}
	return false
}

func (x *JobProgress) GetPercent() float32 {
	if x != nil && x.Percent != nil {
		return *x.Percent
	}
	return 0
}

// JobLog carries raw log output (tee'd git clone / devcontainer up /
// startup-script stdout). level distinguishes the non-fatal WARNING surface
// from info/error.
type JobLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=fleetgrpc.LogLevel" json:"level,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLog) Reset() {
	*x = JobLog{}
	mi := &file_jobs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLog) ProtoMessage() {}

func (x *JobLog) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLog.ProtoReflect.Descriptor instead.
func (*JobLog) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{4}
}

func (x *JobLog) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *JobLog) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *JobLog) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// JobDone is the terminal event. success=false carries the failure message
// persisted as Instance.error (setFailed). instance is the final authoritative
// record (e.g. ContainerID + RUNNING) so the client can update without a
// follow-up GetState. ms is wall-clock duration. warnings are non-fatal
// warnings from a SUCCESSFUL job (also persisted to Instance.warnings).
//
// DESTROY NOTE: for destroy / destroy_fleet the record is gone, so `instance` is
// omitted; success=true even if some teardown failed (best-effort): those are
// JobLog{WARN} + warnings, and the record is removed regardless.
//
// TERMINAL-TRUTH NOTE: the authoritative terminal state is the StateChanged
// snapshot (always shows RUNNING/FAILED); the job stream is best-effort progress
// UI, so a reaped/missed JobDone is harmless.
type JobDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Instance      *Instance              `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
	Ms            int64                  `protobuf:"varint,4,opt,name=ms,proto3" json:"ms,omitempty"`
	Warnings      []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDone) Reset() {
	*x = JobDone{}
	mi := &file_jobs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDone) ProtoMessage() {}

func (x *JobDone) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDone.ProtoReflect.Descriptor instead.
func (*JobDone) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{5}
}

func (x *JobDone) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JobDone) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *JobDone) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *JobDone) GetMs() int64 {
	if x != nil {
		return x.Ms
	}
	return 0
}

func (x *JobDone) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// CreateInstanceRequest mirrors the inputs to create.Run / cli up. The server is
// AUTHORITATIVE: it pre-creates the StatusCreating record itself (no client-side
// state write — this is what eliminates the #63 client-write race), runs the
// job, and streams JobEvents.
//
// BACKEND RESOLUTION: when backend == UNSPECIFIED the server resolves it (since
// ParseBackendType rejects empty today): use config.json DefaultBackend if set
// and valid, else BACKEND_TYPE_DEVCONTAINER. config.json is server-owned (see
// config.proto), so this source is part of the contract, not hidden fs access.
type CreateInstanceRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// git URL; optional — for an existing fleet the server resolves it from the
	// fleet record.
	Remote  *string     `protobuf:"bytes,3,opt,name=remote,proto3,oneof" json:"remote,omitempty"`
	Backend BackendType `protobuf:"varint,4,opt,name=backend,proto3,enum=fleetgrpc.BackendType" json:"backend,omitempty"`
	Branch  *string     `protobuf:"bytes,5,opt,name=branch,proto3,oneof" json:"branch,omitempty"`
	Verbose bool        `protobuf:"varint,6,opt,name=verbose,proto3" json:"verbose,omitempty"`
	// Absolute path (on the DAEMON host) of an existing folder to use as the
	// project root, bind-mounted IN PLACE instead of git-cloning a remote. When
	// set, the instance is a "local folder" instance: no clone, the folder is the
	// workspace, and edits flow both ways. Mutually exclusive with remote/branch;
	// its presence is what marks the instance/fleet as local-folder.
	SourcePath    *string `protobuf:"bytes,7,opt,name=source_path,json=sourcePath,proto3,oneof" json:"source_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_jobs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{6}
}

func (x *CreateInstanceRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *CreateInstanceRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *CreateInstanceRequest) GetRemote() string {
	if x != nil && x.Remote != nil {
		return *x.Remote
	}
	return ""
}

func (x *CreateInstanceRequest) GetBackend() BackendType {
	if x != nil {
		return x.Backend
	}
	return BackendType_BACKEND_TYPE_UNSPECIFIED
}

func (x *CreateInstanceRequest) GetBranch() string {
	if x != nil && x.Branch != nil {
		return *x.Branch
	}
	return ""
}

func (x *CreateInstanceRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *CreateInstanceRequest) GetSourcePath() string {
	if x != nil && x.SourcePath != nil {
		return *x.SourcePath
	}
	return ""
}

// DestroyInstanceRequest destroys a single instance, or (destroy_fleet=true)
// tears down EVERY instance in the fleet and removes the fleet record in one
// job: down each container (BACKEND_DOWN), os.RemoveAll each workspace
// (REMOVE_WORKSPACE), then remove the record. Best-effort: container/workspace
// failures are JobLog{WARN} + JobDone.warnings and the record is removed anyway.
type DestroyInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      *string                `protobuf:"bytes,2,opt,name=instance,proto3,oneof" json:"instance,omitempty"`
	DestroyFleet  bool                   `protobuf:"varint,3,opt,name=destroy_fleet,json=destroyFleet,proto3" json:"destroy_fleet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyInstanceRequest) Reset() {
	*x = DestroyInstanceRequest{}
	mi := &file_jobs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyInstanceRequest) ProtoMessage() {}

func (x *DestroyInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyInstanceRequest.ProtoReflect.Descriptor instead.
func (*DestroyInstanceRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyInstanceRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *DestroyInstanceRequest) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

func (x *DestroyInstanceRequest) GetDestroyFleet() bool {
	if x != nil {
		return x.DestroyFleet
	}
	return false
}

type StartInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceRequest) Reset() {
	*x = StartInstanceRequest{}
	mi := &file_jobs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceRequest) ProtoMessage() {}

func (x *StartInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceRequest.ProtoReflect.Descriptor instead.
func (*StartInstanceRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{8}
}

func (x *StartInstanceRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *StartInstanceRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

// RebuildInstanceRequest recreates one instance's container in place. The
// backend tears down and reprovisions the container (devcontainer: `devcontainer
// up --remove-existing-container`; codespaces: `gh codespace rebuild`) while
// PRESERVING the workspace — the git checkout, uncommitted edits, and mounted
// state survive. Fleet then re-runs the post-Up provisioning (fleet-launch
// staging, dotfiles, startup scripts, Claude hooks) so the fresh container is
// equivalent to a freshly created one. Backends whose runtime has no rebuild
// primitive (coder) reject the job. Unlike destroy, the record is kept and
// flips back to RUNNING (or FAILED) on completion.
type RebuildInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildInstanceRequest) Reset() {
	*x = RebuildInstanceRequest{}
	mi := &file_jobs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildInstanceRequest) ProtoMessage() {}

func (x *RebuildInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildInstanceRequest.ProtoReflect.Descriptor instead.
func (*RebuildInstanceRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{9}
}

func (x *RebuildInstanceRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *RebuildInstanceRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type StopInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceRequest) Reset() {
	*x = StopInstanceRequest{}
	mi := &file_jobs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceRequest) ProtoMessage() {}

func (x *StopInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceRequest.ProtoReflect.Descriptor instead.
func (*StopInstanceRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{10}
}

func (x *StopInstanceRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *StopInstanceRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

// CloneInstanceRequest clones a running source instance into a new one.
//
// COPY CONTRACT (authoritative — reproduces cli/clone.go + tui/dialogs.go): the
// server READS the source record and copies Config, Backend, Tag, Color, and
// Branch into the new instance; DisplayName is set from new_display_name
// (falling back to new_instance); Status starts as CLONING. The optional
// override fields override the copied Tag/Color/Branch without clobbering the
// rest; absent override == use the source value.
type CloneInstanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Fleet          string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	SourceInstance string                 `protobuf:"bytes,2,opt,name=source_instance,json=sourceInstance,proto3" json:"source_instance,omitempty"`
	NewInstance    string                 `protobuf:"bytes,3,opt,name=new_instance,json=newInstance,proto3" json:"new_instance,omitempty"`
	NewDisplayName *string                `protobuf:"bytes,4,opt,name=new_display_name,json=newDisplayName,proto3,oneof" json:"new_display_name,omitempty"`
	TagOverride    *string                `protobuf:"bytes,5,opt,name=tag_override,json=tagOverride,proto3,oneof" json:"tag_override,omitempty"`
	ColorOverride  *string                `protobuf:"bytes,6,opt,name=color_override,json=colorOverride,proto3,oneof" json:"color_override,omitempty"`
	BranchOverride *string                `protobuf:"bytes,7,opt,name=branch_override,json=branchOverride,proto3,oneof" json:"branch_override,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CloneInstanceRequest) Reset() {
	*x = CloneInstanceRequest{}
	mi := &file_jobs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneInstanceRequest) ProtoMessage() {}

func (x *CloneInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneInstanceRequest.ProtoReflect.Descriptor instead.
func (*CloneInstanceRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{11}
}

func (x *CloneInstanceRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *CloneInstanceRequest) GetSourceInstance() string {
	if x != nil {
		return x.SourceInstance
	}
	return ""
}

func (x *CloneInstanceRequest) GetNewInstance() string {
	if x != nil {
		return x.NewInstance
	}
	return ""
}

func (x *CloneInstanceRequest) GetNewDisplayName() string {
	if x != nil && x.NewDisplayName != nil {
		return *x.NewDisplayName
	}
	return ""
}

func (x *CloneInstanceRequest) GetTagOverride() string {
	if x != nil && x.TagOverride != nil {
		return *x.TagOverride
	}
	return ""
}

func (x *CloneInstanceRequest) GetColorOverride() string {
	if x != nil && x.ColorOverride != nil {
		return *x.ColorOverride
	}
	return ""
}

func (x *CloneInstanceRequest) GetBranchOverride() string {
	if x != nil && x.BranchOverride != nil {
		return *x.BranchOverride
	}
	return ""
}

var File_jobs_proto protoreflect.FileDescriptor

const file_jobs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"jobs.proto\x12\tfleetgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fdomain.proto\"\xef\x01\n" +
	"\n" +
	"JobSummary\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.fleetgrpc.JobKindR\x04kind\x12\x14\n" +
	"\x05fleet\x18\x03 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x04 \x01(\tR\binstance\x125\n" +
	"\fcurrent_step\x18\x05 \x01(\x0e2\x12.fleetgrpc.JobStepR\vcurrentStep\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xe4\x01\n" +
	"\bJobEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x121\n" +
	"\astarted\x18\x02 \x01(\v2\x15.fleetgrpc.JobStartedH\x00R\astarted\x124\n" +
	"\bprogress\x18\x03 \x01(\v2\x16.fleetgrpc.JobProgressH\x00R\bprogress\x12%\n" +
	"\x03log\x18\x04 \x01(\v2\x11.fleetgrpc.JobLogH\x00R\x03log\x12(\n" +
	"\x04done\x18\x05 \x01(\v2\x12.fleetgrpc.JobDoneH\x00R\x04doneB\a\n" +
	"\x05event\"\xb8\x01\n" +
	"\n" +
	"JobStarted\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.fleetgrpc.JobKindR\x04kind\x12\x14\n" +
	"\x05fleet\x18\x03 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x04 \x01(\tR\binstance\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\x97\x01\n" +
	"\vJobProgress\x12&\n" +
	"\x04step\x18\x01 \x01(\x0e2\x12.fleetgrpc.JobStepR\x04step\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tstep_done\x18\x03 \x01(\bR\bstepDone\x12\x1d\n" +
	"\apercent\x18\x04 \x01(\x02H\x00R\apercent\x88\x01\x01B\n" +
	"\n" +
	"\b_percent\"s\n" +
	"\x06JobLog\x12)\n" +
	"\x05level\x18\x01 \x01(\x0e2\x13.fleetgrpc.LogLevelR\x05level\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\xa5\x01\n" +
	"\aJobDone\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12/\n" +
	"\binstance\x18\x03 \x01(\v2\x13.fleetgrpc.InstanceR\binstance\x12\x0e\n" +
	"\x02ms\x18\x04 \x01(\x03R\x02ms\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarningsB\b\n" +
	"\x06_error\"\x9b\x02\n" +
	"\x15CreateInstanceRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x1b\n" +
	"\x06remote\x18\x03 \x01(\tH\x00R\x06remote\x88\x01\x01\x120\n" +
	"\abackend\x18\x04 \x01(\x0e2\x16.fleetgrpc.BackendTypeR\abackend\x12\x1b\n" +
	"\x06branch\x18\x05 \x01(\tH\x01R\x06branch\x88\x01\x01\x12\x18\n" +
	"\averbose\x18\x06 \x01(\bR\averbose\x12$\n" +
	"\vsource_path\x18\a \x01(\tH\x02R\n" +
	"sourcePath\x88\x01\x01B\t\n" +
	"\a_remoteB\t\n" +
	"\a_branchB\x0e\n" +
	"\f_source_path\"\x81\x01\n" +
	"\x16DestroyInstanceRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1f\n" +
	"\binstance\x18\x02 \x01(\tH\x00R\binstance\x88\x01\x01\x12#\n" +
	"\rdestroy_fleet\x18\x03 \x01(\bR\fdestroyFleetB\v\n" +
	"\t_instance\"H\n" +
	"\x14StartInstanceRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\"J\n" +
	"\x16RebuildInstanceRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\"G\n" +
	"\x13StopInstanceRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\"\xf6\x02\n" +
	"\x14CloneInstanceRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12'\n" +
	"\x0fsource_instance\x18\x02 \x01(\tR\x0esourceInstance\x12!\n" +
	"\fnew_instance\x18\x03 \x01(\tR\vnewInstance\x12-\n" +
	"\x10new_display_name\x18\x04 \x01(\tH\x00R\x0enewDisplayName\x88\x01\x01\x12&\n" +
	"\ftag_override\x18\x05 \x01(\tH\x01R\vtagOverride\x88\x01\x01\x12*\n" +
	"\x0ecolor_override\x18\x06 \x01(\tH\x02R\rcolorOverride\x88\x01\x01\x12,\n" +
	"\x0fbranch_override\x18\a \x01(\tH\x03R\x0ebranchOverride\x88\x01\x01B\x13\n" +
	"\x11_new_display_nameB\x0f\n" +
	"\r_tag_overrideB\x11\n" +
	"\x0f_color_overrideB\x12\n" +
	"\x10_branch_override*\xd5\x01\n" +
	"\aJobKind\x12\x18\n" +
	"\x14JOB_KIND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18JOB_KIND_CREATE_INSTANCE\x10\x01\x12\x1d\n" +
	"\x19JOB_KIND_DESTROY_INSTANCE\x10\x02\x12\x1b\n" +
	"\x17JOB_KIND_START_INSTANCE\x10\x03\x12\x1a\n" +
	"\x16JOB_KIND_STOP_INSTANCE\x10\x04\x12\x1b\n" +
	"\x17JOB_KIND_CLONE_INSTANCE\x10\x05\x12\x1d\n" +
	"\x19JOB_KIND_REBUILD_INSTANCE\x10\x06*\xca\x04\n" +
	"\aJobStep\x12\x18\n" +
	"\x14JOB_STEP_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19JOB_STEP_VALIDATE_BACKEND\x10\x01\x12\x1a\n" +
	"\x16JOB_STEP_BUILD_BACKEND\x10\x02\x12\x16\n" +
	"\x12JOB_STEP_GIT_CLONE\x10\x03\x12\x1b\n" +
	"\x17JOB_STEP_RESOLVE_MOUNTS\x10\x04\x12\x1a\n" +
	"\x16JOB_STEP_CONTROL_MOUNT\x10\x05\x12\x17\n" +
	"\x13JOB_STEP_BACKEND_UP\x10\x06\x12\x1f\n" +
	"\x1bJOB_STEP_STAGE_FLEET_LAUNCH\x10\a\x12\x1b\n" +
	"\x17JOB_STEP_STAGE_FLEET_RC\x10\b\x12!\n" +
	"\x1dJOB_STEP_APPLY_MOUNT_SYMLINKS\x10\t\x12\x1d\n" +
	"\x19JOB_STEP_INSTALL_DOTFILES\x10\n" +
	"\x12 \n" +
	"\x1cJOB_STEP_RUN_STARTUP_SCRIPTS\x10\v\x12!\n" +
	"\x1dJOB_STEP_INSTALL_CLAUDE_HOOKS\x10\f\x12\x1b\n" +
	"\x17JOB_STEP_COPY_WORKSPACE\x10\r\x12\x1a\n" +
	"\x16JOB_STEP_BACKEND_CLONE\x10\x0e\x12\x19\n" +
	"\x15JOB_STEP_BACKEND_DOWN\x10\x0f\x12\x1d\n" +
	"\x19JOB_STEP_REMOVE_WORKSPACE\x10\x10\x12\x1a\n" +
	"\x16JOB_STEP_BACKEND_START\x10\x11\x12\x19\n" +
	"\x15JOB_STEP_MARK_RUNNING\x10\x12\x12\x11\n" +
	"\rJOB_STEP_DONE\x10\x13*b\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x02\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x03B:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var (
	file_jobs_proto_rawDescOnce sync.Once
	file_jobs_proto_rawDescData []byte
)

func file_jobs_proto_rawDescGZIP() []byte {
	file_jobs_proto_rawDescOnce.Do(func() {
		file_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobs_proto_rawDesc), len(file_jobs_proto_rawDesc)))
	})
	return file_jobs_proto_rawDescData
}

var file_jobs_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_jobs_proto_goTypes = []any{
	(JobKind)(0),                   // 0: fleetgrpc.JobKind
	(JobStep)(0),                   // 1: fleetgrpc.JobStep
	(LogLevel)(0),                  // 2: fleetgrpc.LogLevel
	(*JobSummary)(nil),             // 3: fleetgrpc.JobSummary
	(*JobEvent)(nil),               // 4: fleetgrpc.JobEvent
	(*JobStarted)(nil),             // 5: fleetgrpc.JobStarted
	(*JobProgress)(nil),            // 6: fleetgrpc.JobProgress
	(*JobLog)(nil),                 // 7: fleetgrpc.JobLog
	(*JobDone)(nil),                // 8: fleetgrpc.JobDone
	(*CreateInstanceRequest)(nil),  // 9: fleetgrpc.CreateInstanceRequest
	(*DestroyInstanceRequest)(nil), // 10: fleetgrpc.DestroyInstanceRequest
	(*StartInstanceRequest)(nil),   // 11: fleetgrpc.StartInstanceRequest
	(*RebuildInstanceRequest)(nil), // 12: fleetgrpc.RebuildInstanceRequest
	(*StopInstanceRequest)(nil),    // 13: fleetgrpc.StopInstanceRequest
	(*CloneInstanceRequest)(nil),   // 14: fleetgrpc.CloneInstanceRequest
	(*timestamppb.Timestamp)(nil),  // 15: google.protobuf.Timestamp
	(*Instance)(nil),               // 16: fleetgrpc.Instance
	(BackendType)(0),               // 17: fleetgrpc.BackendType
}
var file_jobs_proto_depIdxs = []int32{
	0,  // 0: fleetgrpc.JobSummary.kind:type_name -> fleetgrpc.JobKind
	1,  // 1: fleetgrpc.JobSummary.current_step:type_name -> fleetgrpc.JobStep
	15, // 2: fleetgrpc.JobSummary.started_at:type_name -> google.protobuf.Timestamp
	5,  // 3: fleetgrpc.JobEvent.started:type_name -> fleetgrpc.JobStarted
	6,  // 4: fleetgrpc.JobEvent.progress:type_name -> fleetgrpc.JobProgress
	7,  // 5: fleetgrpc.JobEvent.log:type_name -> fleetgrpc.JobLog
	8,  // 6: fleetgrpc.JobEvent.done:type_name -> fleetgrpc.JobDone
	0,  // 7: fleetgrpc.JobStarted.kind:type_name -> fleetgrpc.JobKind
	15, // 8: fleetgrpc.JobStarted.started_at:type_name -> google.protobuf.Timestamp
	1,  // 9: fleetgrpc.JobProgress.step:type_name -> fleetgrpc.JobStep
	2,  // 10: fleetgrpc.JobLog.level:type_name -> fleetgrpc.LogLevel
	15, // 11: fleetgrpc.JobLog.at:type_name -> google.protobuf.Timestamp
	16, // 12: fleetgrpc.JobDone.instance:type_name -> fleetgrpc.Instance
	17, // 13: fleetgrpc.CreateInstanceRequest.backend:type_name -> fleetgrpc.BackendType
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_jobs_proto_init() }
func file_jobs_proto_init() {
	if File_jobs_proto != nil {
		return
	}
	file_domain_proto_init()
	file_jobs_proto_msgTypes[1].OneofWrappers = []any{
		(*JobEvent_Started)(nil),
		(*JobEvent_Progress)(nil),
		(*JobEvent_Log)(nil),
		(*JobEvent_Done)(nil),
	}
	file_jobs_proto_msgTypes[3].OneofWrappers = []any{}
	file_jobs_proto_msgTypes[5].OneofWrappers = []any{}
	file_jobs_proto_msgTypes[6].OneofWrappers = []any{}
	file_jobs_proto_msgTypes[7].OneofWrappers = []any{}
	file_jobs_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobs_proto_rawDesc), len(file_jobs_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jobs_proto_goTypes,
		DependencyIndexes: file_jobs_proto_depIdxs,
		EnumInfos:         file_jobs_proto_enumTypes,
		MessageInfos:      file_jobs_proto_msgTypes,
	}.Build()
	File_jobs_proto = out.File
	file_jobs_proto_goTypes = nil
	file_jobs_proto_depIdxs = nil
}
